FROM registry.gitlab.com/dedyms/ampache:build AS cache

FROM registry.gitlab.com/dedyms/nginx:sid
COPY --chown=$CONTAINERUSER:$CONTAINERUSER --from=cache /var/www/html /var/www/html
COPY default.conf /etc/nginx/conf.d/default.conf
USER $CONTAINERUSER
WORKDIR /var/www/html
VOLUME /var/www/html/config
